# KNNClassifier

## Importing Packages

In [ ]:
import pandas as pd
import numpy as np
import math
from collections import Counter
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from matplotlib import pyplot as plt

## Splitting Dataset into training and validation set

In [4]:
def train_test_split(df,test_size):
    if(isinstance(test_size,float)==False):
        print('pass test_size in percent/100')
        return
    test_size=math.floor(len(df)*test_size)
    size=len(df)-test_size
    global test_frame
    global train_frame
    global test_labels
    global train_labels
    test_frame=df.iloc[size:,1:].values
    train_frame=df.iloc[:size,1:].values
    test_labels=df.iloc[size:,:1].values
    train_labels=df.iloc[:size,:1].values

In [6]:
def count1(List): 
    occurence_count = Counter(List) 
    return occurence_count.most_common(1)[0][0]

## Distance Metrics

### Eucledian Distance

In [8]:
def eucledianDist(train_frame,test_frame,train_labels,k):
    predicted_label=[]
    for i in test_frame:
        result=[]
        index=0
        for j in train_frame:
            eudist=0.0
            val=np.linalg.norm(i-j)
            result.append((val,int(train_labels[index])))
            index+=1
        result.sort()
        klist=[]
        for p in range(0,k):
            klist.append(result[p][1])
        resval=count1(klist)
        predicted_label.append(resval)
    return predicted_label    

### Manhattan Distance

In [10]:
def manhattan_dist(train_frame,test_frame,train_labels,k):
    predicted_label=[]
    for i in test_frame:
        result=[]
        index=0
        for j in train_frame:
            eudist=0.0
            val=sum(abs(i-j))
            result.append((val,int(train_labels[index])))
            index+=1
        result.sort()
        klist=[]
        for p in range(k+1):
            klist.append(result[p][1])
        resval=count1(klist)
        predicted_label.append(resval)
    return predicted_label

In [12]:
def findAccuracy(predLabels,actualLabels):
    count=0
    actualSize=len(actualLabels)
    #print(actualSize)
    for i in range(len(predLabels)):
        if(predLabels[i]==actualLabels[i]):
            count+=1
    accuracy=(count/actualSize)*100
    print(accuracy)

## Performances Metrics

### Confusion Matrix and F1 Score

In [14]:
df=pd.read_csv('train.csv',header=None)
train_test_split(df,.2)
# print(len(test_labels))
predlist=eucledianDist(train_frame,test_frame,train_labels,3)
# print(len(predlist))
findAccuracy(predlist,test_labels)
mat=confusion_matrix(predlist,test_labels)
print (mat)
score=f1_score(predlist,test_labels, average='micro')
print(score)

95.45
[[414   0   2   0   0   2   1   0   0   1]
 [  0 453   7   2   3   0   1   3   7   1]
 [  0   1 347   1   0   1   1   0   1   0]
 [  0   1   3 387   0  10   0   0  10   2]
 [  0   1   0   0 371   1   0   2   1   5]
 [  0   0   1   7   0 335   4   0  11   2]
 [  2   0   5   0   3   6 370   0   2   1]
 [  0   2  10   1   0   0   0 388   0  12]
 [  0   0   2   5   0   3   0   0 349   0]
 [  0   0   2   3  15   4   0   4   4 404]]
0.9545


## Graphs

In [ ]:
plt.figure(0)
plt.suptitle('k-Nearest Neighbour Plot', fontsize=10)
plt.plot(predlist)
plt.xlabel('Neighbours', fontsize=16)
plt.ylabel('Accuracy', fontsize=16)
plt.rcParams['figure.figsize']=20,6
plt.show()

### Majority Voting Technique

In [17]:
import statistics
from statistics import mode
df1=pd.read_csv('train.csv',header=None)
train_test_split(df1,.2)
listOfTrainLabels=[]
for i in train_labels:
    listOfTrainLabels.append(i[0])
val=mode(listOfTrainLabels)
print(val)
predListMajorityVoting=[val]*len(test_labels)
# print(predList)
findAccuracy(predListMajorityVoting,test_labels)

1
11.450000000000001


### Random Guessing voting Technique

In [19]:
import random  
predListRandomguessing =[random.randrange(0, 10, 1) for i in range(len(test_labels))]
# print(predListRandomguessing)
findAccuracy(predListRandomguessing,test_labels)

9.925


In [20]:
#random guessing performance on validation set
#95.75 3 5 95.55 1 95.55

## Accuracy using Scikit Learn library kNN classifier : 

In [12]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
df1=pd.read_csv('train.csv',header=None)
output=df1.iloc[0:,0]
x_train=df1.iloc[0:,1:]
# print(output)
def BuiltInKNN(k):
        nearSat = KNeighborsClassifier(n_neighbors=k)
        nearSat.fit(x_train,output)
        y_pred = nearSat.predict(x_train)
        print(metrics.accuracy_score(output, y_pred))
        
BuiltInKNN(3)



0.98075
